spring:
  application:
    name: mscards
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: test
    password:
    url: jdbc:h2:mem:test

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance_id:${random.value}}
