spring:
  application:
    name: mscreditvalidator
  rabbitmq:
    virtual-host: /
    host: ${RABBITMQSERVER}
    username: guest
    password: guest
    port: 5672

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance_id:${random.value}}

mq:
  queues:
    card-issuer: card-issuer
